nelmio_api_doc:
    documentation:
        info:
            title: API DOC Clicker Game
            description: Jeu de type Clicker
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:            # arbitrary name for the security scheme this will be use in annotations @Security(name="bearerAuth")
                    type: http
                    scheme: bearer
                    bearerFormat: JWT 
        security:
            - bearerAuth: []
        # https://swagger.io/docs/specification/paths-and-operations/
        paths: 

        #* Route Json Web Token
            /api/login_check:
                post:
                    summary: Auth method
                    description: authenticate method
                    # https://swagger.io/docs/specification/grouping-operations-with-tags/
                    tags:
                        - Clicker API Auth
                    # https://swagger.io/docs/specification/describing-parameters/
                    requestBody:
                        description: JSON Object
                        required: true
                        content: 
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: JWT Token
                            content:
                                application/json:
                                    schema: 
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            
        #* Entity User
            #! Routes User GET  
            #? Show One User By ID                                            
            /api/user/{id}:
                get:
                    summary: Show One User By ID   
                    description: Show One User By ID Methods
                    tags:
                        - Sound'Clock API User
                    parameters:
                      - in: path
                        name: id
                        schema:
                            type: integer
                        required: true

                    responses:
                        '200':
                            description: Show One User By ID
                            content:
                                application/json:
                                    schema: 
                                        type: array
                                        items: 
                                            type: string

            #? Show One User By ID                                            
            /api/user/slug/{slug}:
                get:
                    summary: Show One User By Slug   
                    description: Show One User By Slug Methods
                    tags:
                        - Sound'Clock API User

                    responses:
                        '200':
                            description: Show One User By Slug
                            content:
                                application/json:
                                    schema: 
                                        type: array
                                        items: 
                                            type: string

            #! Routes User POST  
            #? Add User                                            
            /api/user/create:
                post:
                    summary: Creat User
                    description: Creat User Method 
                    tags:
                        - Sound'Clock API User
                    requestBody:
                        description: application/json
                        required: true
                        content: 
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        nameUser:
                                            type: string
                                        email:
                                            type: string
                                        password:
                                            type: string
